feat(adapter): AWS Lambda Adapter supports requests via Lambda Function URLs.
honojs/hono pull request #1076
Opened 2023-05-07 10:52 UTC by watany-dev

Lambda Function URLs are endpoints that allow for simple requests to be passed to Lambda without an API Gateway. 

https://aws.amazon.com/jp/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/

Most of the event is compatible with API Gateway, but the location of the method is different, which is why, as mentioned in https://github.com/honojs/hono/issues/1075, we specified the behavior of GET during a POST request. This patch attempts to fix that issue.

2023-05-08 05:30 UTC, yusukebe commented
Hi @watany-dev !

Thank you for the PR. I'd like to try running the application with this PR in my environment. So, please wait until I've done it.

2023-05-09 12:32 UTC, yusukebe requested changes
Hi @watany-dev !

Thank you for the PR.

As you pointed out, POST is not working on Lambda Function URLs, so this change seems to fix it. I've left a comment; please check it!

2023-05-09 12:32 UTC, yusukebe commented on src/adapter/aws-lambda/handler.ts
> +    method: event.httpMethod ?? event.requestContext.http?.httpMethod,
I tried it, but `event.requestContext.http?.httpMethod` is `undefined`. So, `method` must be:

```ts
const method = 'httpMethod' in event ? event.httpMethod : event.requestContext.http.method
```

2023-05-09 13:05 UTC, watany-dev commented
I have reviewed the workflow and understood the need to perform runtime tests. I have made the necessary modifications.

2023-05-10 05:29 UTC, watany-dev commented
Sorry, I fixed the Format.

2023-05-10 05:37 UTC, yusukebe approved these changes

2023-05-10 05:38 UTC, yusukebe commented
Thanks! I'll merge it now!

2023-05-10 05:38 UTC, merged