fix: error to retrieve cookie
honojs/hono pull request #1386
Opened 2023-08-29 22:34 UTC by uaichat

TypeError: Cannot read properties of undefined (reading 'split')

### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `yarn denoify` to generate files for Deno

2023-08-30 05:11 UTC, yusukebe requested changes

2023-08-30 05:11 UTC, yusukebe commented on src/helper/cookie/index.ts
> +  const obj = parse(cookie, key)
This change is not necessary.

2023-08-30 05:18 UTC, yusukebe commented
Hi @uaichat 

Thank you for the PR.

I've left a comment and there are two things what you want to do:

1. Add a test.

Please add the following test in `src/helper/cookie/index.ts`:

```ts
    describe('get null if the value is undefined', () => {
      const app = new Hono()

      app.get('/cookie', (c) => {
        const yummyCookie = getCookie(c, 'yummy_cookie')
        const res = new Response('Good cookie')
        if (yummyCookie) res.headers.set('Yummy-Cookie', yummyCookie)
        return res
      })

      it('Should be null', async () => {
        const req = new Request('http://localhost/cookie')
        const cookieString = 'yummy_cookie='
        req.headers.set('Cookie', cookieString)
        const res = await app.request(req)
        expect(res.headers.get('Yummy-Cookie')).toBe(null)
      })
    })
```

2. `denoify`

Please run `denoify` on the root directory and git add&commit&push it.

2023-09-17 23:40 UTC, CyberFlameGO commented
@yusukebe is the option for maintainer edits enabled on their branch? Perhaps you could add said test and merge it instead of waiting if so as the PR seems stale :)

2023-09-18 01:34 UTC, yusukebe commented
@CyberFlameGO 

Ah, yes. It's enabled. I'll fix and merge this later!

2023-09-18 22:18 UTC, yusukebe approved these changes

2023-09-18 22:23 UTC, merged