feat(adaptor): Support AWS Function URL Streaming
honojs/hono pull request #1625
Opened 2023-10-28 04:37 UTC by watany-dev

fixed: https://github.com/honojs/hono/issues/1183

We were able to run the streaming response by operating this module on the actual machine. Unfortunately, awslambda.streamifyResponse provided by AWS Lambda is globally available in the Lambda Nodejs environment, but no method for local testing is provided.

Therefore, we decided to separate it as streamHandle from the existing handle. This way, even if there's a bug, existing users won't be affected. Whether to release this as 'experimental' or to halt integration until a testing method is established is a challenging decision.

### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `yarn denoify` to generate files for Deno

2023-10-29 20:34 UTC, yusukebe commented
Hi @watany-dev,

> Unfortunately, `awslambda.streamifyResponse` provided by AWS Lambda is globally available in the Lambda Node.js environment, but no method for local testing is provided.

Can we create a fake API for mocking in testing only? For example, the `Cache API` does not exist on Node.js, but we mock it in [this file](https://github.com/honojs/hono/blob/main/src/test-utils/setup-vitest.ts) to test Cache Middleware.

```ts
type StoreMap = Map<string | Request, Response>

class MockCache {
  // ...
}

const globalStore: Map<string | Request, Response> = new Map()

const caches = {
  open: (name: string) => {
    return new MockCache(name, globalStore)
  },
}

vi.stubGlobal('caches', caches)
```

I think it's OK to mock that are difficult to reproduce depending on the specific environment.

2023-11-04 18:33 UTC, watany-dev commented
@yusukebe 
I've taken into account your helpful advice, and I'm pleased to report that the local tests have passed without issue. Thank you.

2023-11-06 00:10 UTC, yusukebe commented
@watany-dev 

Great! Looks good. I'll merge this later.

2023-11-06 00:11 UTC, yusukebe requested changes

2023-11-06 00:11 UTC, yusukebe commented on .pre-commit-config.yaml
You forgot remove this?

2023-11-06 00:12 UTC, yusukebe commented on .pre-commit-config.yaml
Ah, sorry. Already removed.

2023-11-06 00:13 UTC, yusukebe approved these changes

2023-11-06 22:05 UTC, yusukebe commented
It's a time for merging! I'll merge this into the "next" branch and will release a RC version first. Thanks!

2023-11-06 22:05 UTC, merged