feat(request): Introduce `matchedRoutes` and `routePath` for `HonoRequest`
honojs/hono pull request #1744
Opened 2023-11-29 03:10 UTC by usualoma

```ts
app.use('*', async function logger(c, next) {
  await next()
  c.req.matchedRoutes.forEach(({ handler, method, path }, i) => {
    const name = handler.name || (handler.length < 2 ? '[handler]' : '[middleware]')
    console.log(
      method,
      ' ',
      path,
      ' '.repeat(Math.max(10 - path.length, 0)),
      name,
      i === c.req.routeIndex ? '<- respond from here' : ''
    )
  })
})
app.use('*', async function namedMiddleware(c, next) {
  await next()
})
app.get('/*', async (c, next) => await next())
app.get('/hi/:name', (c) => c.json({ name: c.req.param('name'), path: c.req.routePath }))
```

```
% bun run --hot app.ts
Started server http://localhost:3000
ALL   /*          logger 
ALL   /*          namedMiddleware 
GET   /hi/*       [middleware] 
GET   /hi/:name   [handler] <- respond from here
```

```
% curl http://localhost:3000/hi/hono
{"name":"hono","path":"/hi/:name"}
```

### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

2023-12-01 20:27 UTC, yusukebe commented
@usualoma 

Could you resolve the conflicts?

2023-12-01 22:45 UTC, usualoma commented
@yusukebe Oops. Resolved!

2023-12-03 08:44 UTC, yusukebe requested changes

2023-12-03 08:44 UTC, yusukebe commented on src/request.ts
>  import type { ParamIndexMap, ParamStash, Params } from './router'
Can you remove these lines?

```ts
/* eslint-disable @typescript-eslint/no-non-null-assertion */
import type { ParamIndexMap, ParamStash, Params } from './router'
```

2023-12-03 08:47 UTC, yusukebe commented
Hi @usualoma 

This is great. I like the minimal changes to the code and the features are implemented, `Context` and routers are not changed.

I made only one comment. Check it. Thanks!

2023-12-03 09:51 UTC, usualoma commented
@yusukebe Thank you for your review. These changes would improve DX.
Fixed problem in 4c596ac!

2023-12-03 09:54 UTC, yusukebe approved these changes

2023-12-03 09:55 UTC, yusukebe commented
Thanks!

Okay, merge now. Maybe I'll release the next minor version "v3.11.0" soon.

2023-12-03 09:55 UTC, merged